In [3]:
n = 156
c = 10


n =

   156


c =

    10



In [14]:
n = floor(n); %falls nich eine Naturliche Zahl eingegeben wird
bin = [];
tmp = n;
output = [];
%berechnen n in base 2
while tmp > 0
    rem = mod(tmp, 2);
    bin = [rem;bin];
    tmp = floor(tmp/2);
end
bin
%Vektor laenge c erzeugen
l = length(bin)
if l >= c
    y = bin((end-c+1):end);
else
    z = zeros(c-l,1);
    y = [z;bin];
end
y


bin =

     1
     0
     0
     1
     1
     1
     0
     0


l =

     8


z =

     0
     0


y =

     0
     0
     1
     0
     0
     1
     1
     1
     0
     0


y =

     0
     0
     1
     0
     0
     1
     1
     1
     0
     0



In [7]:
ntobasetwo(156,10)


ans =

     0
     0
     1
     0
     0
     1
     1
     1
     0
     0



In [4]:
i1 = [0 0 1 1]
i2 = [1 0 1 1]
n = i2;


i1 =

     0     0     1     1


i2 =

     1     0     1     1



In [20]:
%Zweierkomplement: umklappen und 1 addieren

tmp = n;

%umklappen
for i = 1:length(tmp)
    if tmp(i) == 1
        tmp(i) = 0;
    else
        tmp(i) = 1;
    end
end

%1 addieren
for i = length(tmp):-1:1
    if tmp(i) == 1
        tmp(i) = 0;
    else
        tmp(i) = 1;
        break
    end
end

In [ ]:
complement(n)


ans =

     0     1     0     1



In [6]:
tmp = i1


tmp =

     0     0     1     1



In [ ]:
z = -1


z =

    -1



In [4]:
z = -120
c = 8


z =

  -120


c =

     8



In [10]:
if z < 0
    y = complement(ntobasetwo(abs(z),c))
else
    y = ntobasetwo(z,c)
end


y =

     1
     0
     0
     0
     1
     0
     0
     0



In [11]:
ztobasetwo(z,c)


y =

     1
     0
     0
     0
     1
     0
     0
     0


ans =

     1
     0
     0
     0
     1
     0
     0
     0



In [9]:
complement(ntobasetwo(156,10))


ans =

     1
     1
     0
     1
     1
     0
     0
     1
     0
     0

